const pokemones = [ {id: 0, nombre: "Pikachu", imagen: "./Imagenes/Pikachu.png", bg:"electrico", tipo: "Eléctrico", ataqueFavorito: "Impactrueno", evolucion: "Raichu"},
                    {id: 1, nombre: "Charmander", imagen: "./Imagenes/Charmander.png", bg:"fuego", tipo: "Fuego", ataqueFavorito: "Lanzallamas", evolucion: "Charmeleon y Charizard"},
                    {id: 2, nombre: "Bulbasaur", imagen: "./Imagenes/Bulbasaur.png", bg:"hoja", tipo: "Hoja", ataqueFavorito: "Látigo cepa", evolucion: "Ivysaur y Venasaur"},
                    {id: 3, nombre: "Squirtle", imagen: "./Imagenes/Squirtle.png", bg:"agua", tipo: "Agua", ataqueFavorito: "Hidrobomba", evolucion: "Wartortle y Blastoise"},
                    {id: 4, nombre: "Bagon", imagen: "./Imagenes/Bagon.png", bg:"dragon", tipo: "Dragón", ataqueFavorito: "Garra Dragón", evolucion: "Shelgon y Salamance"},
                    {id: 5, nombre: "Torchic", imagen: "./Imagenes/Torchic.png", bg:"fuego", tipo: "Fuego", ataqueFavorito: "Arañazo", evolucion: "Combusken y Blaiziken"},
                    {id: 6, nombre: "Ekans", imagen: "./Imagenes/Ekans.png", bg:"veneno", tipo: "Veneno", ataqueFavorito: "Restricción", evolucion: "Arbok"},
                    {id: 7, nombre: "Dratini", imagen: "./Imagenes/Dratini.png", bg:"dragon", tipo: "Dragón", ataqueFavorito: "Dragoaliento", evolucion: "Dragonair y Dragonite"},
                    {id: 8, nombre: "Magikarp", imagen: "./Imagenes/Magikarp.png", bg:"agua", tipo: "Agua", ataqueFavorito: "Salpicadura", evolucion: "Gyarados"},
                    {id: 9, nombre: "Abra", imagen: "./Imagenes/Abra.png", bg:"psiquico", tipo: "Psíquico", ataqueFavorito: "Teletransporte", evolucion: "Kadabra y Alakazam"},
                    {id: 10, nombre: "Porygon", imagen: "./Imagenes/Porygon.png", bg:"normal", tipo: "Normal", ataqueFavorito: "Hiperrayo", evolucion: "Porygon2 y Porygon-Z"},
                    {id: 11, nombre: "Horsea", imagen: "./Imagenes/Horsea.png", bg:"agua", tipo: "Agua", ataqueFavorito: "Rayo burbuja", evolucion: "Kingdra"},
                    {id: 12, nombre: "Sudowoodo", imagen: "./Imagenes/Sudowoodo.png", bg:"roca", tipo: "Roca", ataqueFavorito: "Avalancha", evolucion: "No tiene"},
                    {id: 13, nombre: "Aron", imagen: "./Imagenes/Aron.png", bg:"acero-roca", tipo: "Acero/Roca", ataqueFavorito: "Garra metal", evolucion: "Lairon y Aggron"},
                    {id: 14, nombre: "Togepi", imagen: "./Imagenes/Togepi.png", bg:"hada", tipo: "Hada", ataqueFavorito: "Fuerza Lunar", evolucion: "Togetic y Togekiss"},
                    {id: 15, nombre: "Riolu", imagen: "./Imagenes/Riolu.png", bg:"lucha", tipo: "Lucha", ataqueFavorito: "Onda vacío", evolucion: "Lucario"},
                    {id: 16, nombre: "Zorua", imagen: "./Imagenes/Zorua.png", bg:"siniestro", tipo: "Siniestro", ataqueFavorito: "Pulso Noche", evolucion: "Zoroark"},
                    {id: 17, nombre: "Pawniard", imagen: "./Imagenes/Pawniard.png", bg:"siniestro-acero", tipo: "Siniestro/Acero", ataqueFavorito: "Gillotina", evolucion: "Bisharp y Kingambit"},
                    {id: 18, nombre: "Gastly", imagen: "./Imagenes/Gastly.png", bg:"fantasma", tipo: "Fantasma", ataqueFavorito: "Lengüetazo", evolucion: "Hunter y Gengar"},
                    {id: 19, nombre: "Litwick", imagen: "./Imagenes/Litwick.png", bg:"fantasma-fuego", tipo: "Fantasma/Fuego", ataqueFavorito: "Fuego fatuo", evolucion: "Lampent y Chandelure"},
                    {id: 20, nombre: "Scyther", imagen: "./Imagenes/Scyther.png", bg:"bicho-volador", tipo: "Bicho/Volador", ataqueFavorito: "Tijera X", evolucion: "Scizor o Kleavor"},
                    {id: 21, nombre: "Swablu", imagen: "./Imagenes/Swablu.png", bg:"volador-normal", tipo: "Volador/Normal", ataqueFavorito: "Canto", evolucion: "Altaria"},
                    {id: 22, nombre: "Cubone", imagen: "./Imagenes/Cubone.png", bg:"tierra", tipo: "Tierra", ataqueFavorito: "Huesomerang", evolucion: "Marowak"},
                    {id: 23, nombre: "Snorunt", imagen: "./Imagenes/Snorunt.png", bg:"hielo", tipo: "Hielo", ataqueFavorito: "Colmillo hielo", evolucion: "Glalie o Froslass(♀️)"},
                    {id: 24, nombre: "Cufant", imagen: "./Imagenes/Cufant.png", bg:"acero", tipo: "Acero", ataqueFavorito: "Cabeza de hierro", evolucion: "Copperajah"},
                    {id: 25, nombre: "Latios", imagen: "./Imagenes/Latios.png", bg:"dragon-psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Psíquico", evolucion: "No tiene"},
                    {id: 26, nombre: "Latias", imagen: "./Imagenes/Latias.png", bg:"dragon-psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Pulso Dragón", evolucion: "No tiene"}]

const equipo = []