const pokemones = [ {id: 0, nombre:"pikachu" ,imagen: "./Imagenes/Pikachu.png", bTipo:"electrico", tipo: "Eléctrico", ataqueFavorito: "Impactrueno", evolucion: "Raichu"},
                    {id: 1, nombre:"charmander" ,imagen: "./Imagenes/Charmander.png", bTipo:"fuego", tipo: "Fuego", ataqueFavorito: "Lanzallamas", evolucion: "Charmeleon y Charizard"},
                    {id: 2, nombre:"bulbasaur" ,imagen: "./Imagenes/Bulbasaur.png", bTipo:"hoja", tipo: "Hoja", ataqueFavorito: "Látigo cepa", evolucion: "Ivysaur y Venasaur"},
                    {id: 3, nombre:"squirtle" ,imagen: "./Imagenes/Squirtle.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Hidrobomba", evolucion: "Wartortle y Blastoise"},
                    {id: 4, nombre:"bagon" ,imagen: "./Imagenes/Bagon.png", bTipo:"dragon", tipo: "Dragón", ataqueFavorito: "Garra Dragón", evolucion: "Shelgon y Salamance"},
                    {id: 5, nombre:"torchic" ,imagen: "./Imagenes/Torchic.png", bTipo:"fuego", tipo: "Fuego", ataqueFavorito: "Arañazo", evolucion: "Combusken y Blaiziken"},
                    {id: 6, nombre:"ekans" ,imagen: "./Imagenes/Ekans.png", bTipo:"veneno", tipo: "Veneno", ataqueFavorito: "Restricción", evolucion: "Arbok"},
                    {id: 7, nombre:"dratini" ,imagen: "./Imagenes/Dratini.png", bTipo:"dragon", tipo: "Dragón", ataqueFavorito: "Dragoaliento", evolucion: "Dragonair y Dragonite"},
                    {id: 8, nombre:"magikarp" ,imagen: "./Imagenes/Magikarp.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Salpicadura", evolucion: "Gyarados"},
                    {id: 9, nombre:"abra" ,imagen: "./Imagenes/Abra.png", bTipo:"psiquico", tipo: "Psíquico", ataqueFavorito: "Teletransporte", evolucion: "Kadabra y Alakazam"},
                    {id: 10, nombre:"porygon" ,imagen: "./Imagenes/Porygon.png", bTipo:"normal", tipo: "Normal", ataqueFavorito: "Hiperrayo", evolucion: "Porygon2 y Porygon-Z"},
                    {id: 11, nombre:"horsea" ,imagen: "./Imagenes/Horsea.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Rayo burbuja", evolucion: "Kingdra"},
                    {id: 12, nombre:"sudowoodo" ,imagen: "./Imagenes/Sudowoodo.png", bTipo:"roca", tipo: "Roca", ataqueFavorito: "Avalancha", evolucion: "No tiene"},
                    {id: 13, nombre:"aron" ,imagen: "./Imagenes/Aron.png", bTipo:"acero roca", tipo: "Acero/Roca", ataqueFavorito: "Garra metal", evolucion: "Lairon y Aggron"},
                    {id: 14, nombre:"togepi" ,imagen: "./Imagenes/Togepi.png", bTipo:"hada", tipo: "Hada", ataqueFavorito: "Fuerza Lunar", evolucion: "Togetic y Togekiss"},
                    {id: 15, nombre:"riolu" ,imagen: "./Imagenes/Riolu.png", bTipo:"lucha", tipo: "Lucha", ataqueFavorito: "Onda vacío", evolucion: "Lucario"},
                    {id: 16, nombre:"zorua" ,imagen: "./Imagenes/Zorua.png", bTipo:"siniestro", tipo: "Siniestro", ataqueFavorito: "Pulso Noche", evolucion: "Zoroark"},
                    {id: 17, nombre:"pawniard" ,imagen: "./Imagenes/Pawniard.png", bTipo:"siniestro acero", tipo: "Siniestro/Acero", ataqueFavorito: "Gillotina", evolucion: "Bisharp y Kingambit"},
                    {id: 18, nombre:"gastly" ,imagen: "./Imagenes/Gastly.png", bTipo:"fantasma", tipo: "Fantasma", ataqueFavorito: "Lengüetazo", evolucion: "Hunter y Gengar"},
                    {id: 19, nombre:"litwick" ,imagen: "./Imagenes/Litwick.png", bTipo:"fantasma fuego", tipo: "Fantasma/Fuego", ataqueFavorito: "Fuego fatuo", evolucion: "Lampent y Chandelure"},
                    {id: 20, nombre:"scyther" ,imagen: "./Imagenes/Scyther.png", bTipo:"bicho volador", tipo: "Bicho/Volador", ataqueFavorito: "Tijera X", evolucion: "Scizor o Kleavor"},
                    {id: 21, nombre:"swablu" ,imagen: "./Imagenes/Swablu.png", bTipo:"volador normal", tipo: "Volador/Normal", ataqueFavorito: "Canto", evolucion: "Altaria"},
                    {id: 22, nombre:"cubone" ,imagen: "./Imagenes/Cubone.png", bTipo:"tierra", tipo: "Tierra", ataqueFavorito: "Huesomerang", evolucion: "Marowak"},
                    {id: 23, nombre:"snorunt" ,imagen: "./Imagenes/Snorunt.png", bTipo:"hielo", tipo: "Hielo", ataqueFavorito: "Colmillo hielo", evolucion: "Glalie o Froslass(♀️)"},
                    {id: 24, nombre:"cufant" ,imagen: "./Imagenes/Cufant.png", bTipo:"acero", tipo: "Acero", ataqueFavorito: "Cabeza de hierro", evolucion: "Copperajah"},
                    {id: 25, nombre:"latios" ,imagen: "./Imagenes/Latios.png", bTipo:"dragon psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Psíquico", evolucion: "No tiene"},
                    {id: 26, nombre:"latias" ,imagen: "./Imagenes/Latias.png", bTipo:"dragon psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Pulso Dragón", evolucion: "No tiene"}]
const buscadosNombre = []
const buscadosTipo = []
const equipo = []