const pokemones = [ {id: 0, bnombre:"pikachu" ,nombre: "Pikachu", imagen: "./Imagenes/Pikachu.png", bTipo:"electrico", tipo: "Eléctrico", ataqueFavorito: "Impactrueno", evolucion: "Raichu"},
                    {id: 1, bnombre:"charmander" ,nombre: "Charmander", imagen: "./Imagenes/Charmander.png", bTipo:"fuego", tipo: "Fuego", ataqueFavorito: "Lanzallamas", evolucion: "Charmeleon y Charizard"},
                    {id: 2, bnombre:"bulbasaur" ,nombre: "Bulbasaur", imagen: "./Imagenes/Bulbasaur.png", bTipo:"hoja", tipo: "Hoja", ataqueFavorito: "Látigo cepa", evolucion: "Ivysaur y Venasaur"},
                    {id: 3, bnombre:"squirtle" ,nombre: "Squirtle", imagen: "./Imagenes/Squirtle.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Hidrobomba", evolucion: "Wartortle y Blastoise"},
                    {id: 4, bnombre:"bagon" ,nombre: "Bagon", imagen: "./Imagenes/Bagon.png", bTipo:"dragon", tipo: "Dragón", ataqueFavorito: "Garra Dragón", evolucion: "Shelgon y Salamance"},
                    {id: 5, bnombre:"torchic" ,nombre: "Torchic", imagen: "./Imagenes/Torchic.png", bTipo:"fuego", tipo: "Fuego", ataqueFavorito: "Arañazo", evolucion: "Combusken y Blaiziken"},
                    {id: 6, bnombre:"ekans" ,nombre: "Ekans", imagen: "./Imagenes/Ekans.png", bTipo:"veneno", tipo: "Veneno", ataqueFavorito: "Restricción", evolucion: "Arbok"},
                    {id: 7, bnombre:"dratini" ,nombre: "Dratini", imagen: "./Imagenes/Dratini.png", bTipo:"dragon", tipo: "Dragón", ataqueFavorito: "Dragoaliento", evolucion: "Dragonair y Dragonite"},
                    {id: 8, bnombre:"magikarp" ,nombre: "Magikarp", imagen: "./Imagenes/Magikarp.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Salpicadura", evolucion: "Gyarados"},
                    {id: 9, bnombre:"abra" ,nombre: "Abra", imagen: "./Imagenes/Abra.png", bTipo:"psiquico", tipo: "Psíquico", ataqueFavorito: "Teletransporte", evolucion: "Kadabra y Alakazam"},
                    {id: 10, bnombre:"porygon" ,nombre: "Porygon", imagen: "./Imagenes/Porygon.png", bTipo:"normal", tipo: "Normal", ataqueFavorito: "Hiperrayo", evolucion: "Porygon2 y Porygon-Z"},
                    {id: 11, bnombre:"horsea" ,nombre: "Horsea", imagen: "./Imagenes/Horsea.png", bTipo:"agua", tipo: "Agua", ataqueFavorito: "Rayo burbuja", evolucion: "Kingdra"},
                    {id: 12, bnombre:"sudowoodo" ,nombre: "Sudowoodo", imagen: "./Imagenes/Sudowoodo.png", bTipo:"roca", tipo: "Roca", ataqueFavorito: "Avalancha", evolucion: "No tiene"},
                    {id: 13, bnombre:"aron" ,nombre: "Aron", imagen: "./Imagenes/Aron.png", bTipo:"acero roca", tipo: "Acero/Roca", ataqueFavorito: "Garra metal", evolucion: "Lairon y Aggron"},
                    {id: 14, bnombre:"togepi" ,nombre: "Togepi", imagen: "./Imagenes/Togepi.png", bTipo:"hada", tipo: "Hada", ataqueFavorito: "Fuerza Lunar", evolucion: "Togetic y Togekiss"},
                    {id: 15, bnombre:"riolu" ,nombre: "Riolu", imagen: "./Imagenes/Riolu.png", bTipo:"lucha", tipo: "Lucha", ataqueFavorito: "Onda vacío", evolucion: "Lucario"},
                    {id: 16, bnombre:"zorua" ,nombre: "Zorua", imagen: "./Imagenes/Zorua.png", bTipo:"siniestro", tipo: "Siniestro", ataqueFavorito: "Pulso Noche", evolucion: "Zoroark"},
                    {id: 17, bnombre:"pawniard" ,nombre: "Pawniard", imagen: "./Imagenes/Pawniard.png", bTipo:"siniestro acero", tipo: "Siniestro/Acero", ataqueFavorito: "Gillotina", evolucion: "Bisharp y Kingambit"},
                    {id: 18, bnombre:"gastly" ,nombre: "Gastly", imagen: "./Imagenes/Gastly.png", bTipo:"fantasma", tipo: "Fantasma", ataqueFavorito: "Lengüetazo", evolucion: "Hunter y Gengar"},
                    {id: 19, bnombre:"litwick" ,nombre: "Litwick", imagen: "./Imagenes/Litwick.png", bTipo:"fantasma fuego", tipo: "Fantasma/Fuego", ataqueFavorito: "Fuego fatuo", evolucion: "Lampent y Chandelure"},
                    {id: 20, bnombre:"scyther" ,nombre: "Scyther", imagen: "./Imagenes/Scyther.png", bTipo:"bicho volador", tipo: "Bicho/Volador", ataqueFavorito: "Tijera X", evolucion: "Scizor o Kleavor"},
                    {id: 21, bnombre:"swablu" ,nombre: "Swablu", imagen: "./Imagenes/Swablu.png", bTipo:"volador normal", tipo: "Volador/Normal", ataqueFavorito: "Canto", evolucion: "Altaria"},
                    {id: 22, bnombre:"cubone" ,nombre: "Cubone", imagen: "./Imagenes/Cubone.png", bTipo:"tierra", tipo: "Tierra", ataqueFavorito: "Huesomerang", evolucion: "Marowak"},
                    {id: 23, bnombre:"snorunt" ,nombre: "Snorunt", imagen: "./Imagenes/Snorunt.png", bTipo:"hielo", tipo: "Hielo", ataqueFavorito: "Colmillo hielo", evolucion: "Glalie o Froslass(♀️)"},
                    {id: 24, bnombre:"cufant" ,nombre: "Cufant", imagen: "./Imagenes/Cufant.png", bTipo:"acero", tipo: "Acero", ataqueFavorito: "Cabeza de hierro", evolucion: "Copperajah"},
                    {id: 25, bnombre:"latios" ,nombre: "Latios", imagen: "./Imagenes/Latios.png", bTipo:"dragon psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Psíquico", evolucion: "No tiene"},
                    {id: 26, bnombre:"latias" ,nombre: "Latias", imagen: "./Imagenes/Latias.png", bTipo:"dragon psiquico", tipo: "Dragón/Psíquico", ataqueFavorito: "Pulso Dragón", evolucion: "No tiene"}]

const equipo = []